server:
  port: 1003
spring:
  application:
    name: springcloud-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream