server:
  port: 1005
spring:
  application:
    name: springcloud-config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huang-zs/good-good-study-day-day-up/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/